### ISSUE TITLE
Broken links - Govern science / Privacy and security

### ISSUE THREAD

**Issue by kaylatungodden** [huntdatacenter/docs#75]
404 error:
https://docs.hdc.ntnu.no/responsibilities/
https://docs.hdc.ntnu.no/policies/
https://docs.hdc.ntnu.no/certificates/
https://docs.hdc.ntnu.no/subcontractors/

**Comment by JakubNTNU** [comment]
> 404 error: https://docs.hdc.ntnu.no/responsibilities/ https://docs.hdc.ntnu.no/policies/ https://docs.hdc.ntnu.no/certificates/ https://docs.hdc.ntnu.no/subcontractors/

Tested all links, should be working now.
